version: '3.3'

services:
  api: 
    build: .
    image: hotel_manager_api
    ports: 
      - '3000:3000'
    volumes: 
      - .:/usr/src
      - /usr/src/node_modules
    command: npm run start:dev
    container_name: api
    depends_on: 
      - database
  database: 
    image: postgres:13
    environment:
      - POSTGRES_DB=hotel_manager
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    ports: 
      - '5432:5432'
    volumes: 
      - ./postgres_data:/var/lib/postgresql/data
    container_name: db