version: '3.3'

services: 
  database: 
    image: postgres:13
    environment:
      - POSTGRES_DB=hotel_manager
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    ports: 
      - '5432:5432'
    volumes: 
      - ./postgres_data:/var/lib/postgresql/data