name: 'Integration pipeline'

on:
  push: 
    branches: ['production', 'development']
  pull_request:
    branches: ['production', 'development']
    types: [opened, synchronize]

jobs: 
  test: 
    runs-on: ubuntu-20.04
    steps: 
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with: 
          node-version: '14'
      - name: Upgrade NPM
        run: npm install -g npm
      - name: "Install dependencies"
        run : npm ci
      - name: "Lint project"
        run: npm run lint
      - name: "Run tests"
        run: npm run test